name: gg_cache
description: A simple cache method that helps us to cache results of a function.
version: 1.0.8
repository: https://github.com/inlavigo/gg_cache

environment:
  sdk: ^3.2.0

dependencies:
  gg_list: ^2.0.0

dev_dependencies:
  args: ^2.4.2
  coverage: ^1.7.2
  gg_capture_print: ^1.0.2
  lints: ^5.0.0
  test: ^1.24.0
  yaml: ^3.1.2